coverage:
  paths:
    - coverage.out
    - frontend/coverage/lcov.info
codeToTestRatio:
  code:
    - "**/*.go"
    - "!**/*_test.go"
    - "frontend/src/**/*.ts"
    - "frontend/src/**/*.tsx"
    - "!frontend/src/**/*.test.ts"
    - "!frontend/src/**/*.test.tsx"
    - "!frontend/node_modules/**"
  test:
    - "**/*_test.go"
    - "frontend/src/**/*.test.ts"
    - "frontend/src/**/*.test.tsx"
testExecutionTime:
  if: true
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
comment:
  if: is_pull_request
summary:
  if: true
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
